# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-13 20:52
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='parcel',
            fields=[
                ('parcel_number', models.CharField(max_length=7, primary_key=True, serialize=False)),
                ('street_address', models.CharField(max_length=254)),
                ('zipcode', models.CharField(max_length=5)),
                ('improvement_value', models.IntegerField()),
                ('land_value', models.IntegerField()),
                ('property_class', models.CharField(max_length=254)),
                ('homestead_exemption', models.BooleanField(default=False)),
                ('geometry', django.contrib.gis.db.models.fields.MultiPolygonField(srid=2965)),
            ],
        ),
    ]
