# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-14 17:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parcel',
            name='improvement_value',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='land_value',
            field=models.IntegerField(null=True),
        ),
    ]
