# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-17 14:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landlord_registry', '0002_registration_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='applicant_address',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='applicant_company',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='applicant_email',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='applicant_name',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='applicant_phone',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='change_type',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='number_of_units',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='owner_address',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='owner_company',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='owner_email',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='owner_name',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='owner_phone',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='property_name',
        ),
        migrations.AddField(
            model_name='registration',
            name='expiration',
            field=models.DateField(blank=True, default='2000-01-01'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registration',
            name='landlord',
            field=models.CharField(blank=True, max_length=1024),
        ),
        migrations.AddField(
            model_name='registration',
            name='landlord_contact',
            field=models.CharField(blank=True, max_length=1024),
        ),
        migrations.AddField(
            model_name='registration',
            name='manager',
            field=models.CharField(blank=True, max_length=1024),
        ),
        migrations.AddField(
            model_name='registration',
            name='manager_contact',
            field=models.CharField(blank=True, max_length=1024),
        ),
        migrations.AddField(
            model_name='registration',
            name='status',
            field=models.CharField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='registration',
            name='record',
            field=models.CharField(blank=True, max_length=13),
        ),
    ]
